name: databricks_platform
version: 1.0.0
config-version: 2

profile: databricks_platform

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

models:
  databricks_platform:
    staging:
      +materialized: view
      +schema: tymex_platform
    marts:
      +materialized: table
      +schema: tymex_platform

seeds:
  databricks_platform:
    +schema: tymex_platform
